name: On commit workflow
on:
  push:
    jobs:
      Run_tests:
      name: Run unit test
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@master
      - name: Remove package-lock
        run: rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: |
          node_modules/.bin/eslint src/js/**.ts --fix
          node_modules/.bin/eslint src/js/**/**.ts --fix
          node_modules/.bin/eslint src/react/**.ts --fix
          node_modules/.bin/eslint src/react/**/**.ts --fix
      - name: Run unit test
        run: npm test