name: Netlify Storybook Staging Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publishMasterCommit:
    name: Deploying on Netlify Storybook Staging Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.action == 'closed' && github.pull_request.merged == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
        working-directory: ./
      - name: Build storybook
        run: npm run build:storybook
        working-directory: ./
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_ID }}
          deploy_alias: 'staging'
          build_directory: './docs/storybook'
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.WORKFLOW_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://staging--kuc-storybook.netlify.app
