name: Perform traffic logs
on:
  push:
    #every 10:00 UTC+0（19:00 JP Time） 
    
jobs:
  check:
    name: run traffic logs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Generate app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{secrets.TRAFFIC_LOGS_APP_ID}}
          private_key: ${{ secrets.TRAFFIC_LOGS_APP_PRIVATE_KEY }}
      - name: Update config file
        run: |
          sed -i 's|<kintone-app-id>|${{secrets.TRAFFIC_LOGS_KINTONE_APP_ID}}|' config.json
          sed -i 's|<domain>|${{secrets.TRAFFIC_LOGS_KINTONE_APP_DOMAIN}}|' config.json
          sed -i 's|<kintone-app-token>|${{secrets.TRAFFIC_LOGS_KINTONE_APP_API_TOKEN}}|' config.json
        working-directory: traffic-logs
      - name: check release info
        env:
          GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          node traffic-logs-kuc.min.js --config ./config.json
        working-directory: traffic-logs